const COUNTRIES = [
  {
    id: "+500",
    name: "South Georgia",
    cca2: "gs",
    flagUrl: "https://flagcdn.com/w80/gs.png",
  },
  {
    id: "+1473",
    name: "Grenada",
    cca2: "gd",
    flagUrl: "https://flagcdn.com/w80/gd.png",
  },
  {
    id: "+41",
    name: "Switzerland",
    cca2: "ch",
    flagUrl: "https://flagcdn.com/w80/ch.png",
  },
  {
    id: "+232",
    name: "Sierra Leone",
    cca2: "sl",
    flagUrl: "https://flagcdn.com/w80/sl.png",
  },
  {
    id: "+36",
    name: "Hungary",
    cca2: "hu",
    flagUrl: "https://flagcdn.com/w80/hu.png",
  },
  {
    id: "+886",
    name: "Taiwan",
    cca2: "tw",
    flagUrl: "https://flagcdn.com/w80/tw.png",
  },
  {
    id: "+681",
    name: "Wallis and Futuna",
    cca2: "wf",
    flagUrl: "https://flagcdn.com/w80/wf.png",
  },
  {
    id: "+1246",
    name: "Barbados",
    cca2: "bb",
    flagUrl: "https://flagcdn.com/w80/bb.png",
  },
  {
    id: "+64",
    name: "Pitcairn Islands",
    cca2: "pn",
    flagUrl: "https://flagcdn.com/w80/pn.png",
  },
  {
    id: "+225",
    name: "Ivory Coast",
    cca2: "ci",
    flagUrl: "https://flagcdn.com/w80/ci.png",
  },
  {
    id: "+216",
    name: "Tunisia",
    cca2: "tn",
    flagUrl: "https://flagcdn.com/w80/tn.png",
  },
  {
    id: "+39",
    name: "Italy",
    cca2: "it",
    flagUrl: "https://flagcdn.com/w80/it.png",
  },
  {
    id: "+229",
    name: "Benin",
    cca2: "bj",
    flagUrl: "https://flagcdn.com/w80/bj.png",
  },
  {
    id: "+62",
    name: "Indonesia",
    cca2: "id",
    flagUrl: "https://flagcdn.com/w80/id.png",
  },
  {
    id: "+238",
    name: "Cape Verde",
    cca2: "cv",
    flagUrl: "https://flagcdn.com/w80/cv.png",
  },
  {
    id: "+1869",
    name: "Saint Kitts and Nevis",
    cca2: "kn",
    flagUrl: "https://flagcdn.com/w80/kn.png",
  },
  {
    id: "+856",
    name: "Laos",
    cca2: "la",
    flagUrl: "https://flagcdn.com/w80/la.png",
  },
  {
    id: "+599",
    name: "Caribbean Netherlands",
    cca2: "bq",
    flagUrl: "https://flagcdn.com/w80/bq.png",
  },
  {
    id: "+256",
    name: "Uganda",
    cca2: "ug",
    flagUrl: "https://flagcdn.com/w80/ug.png",
  },
  {
    id: "+376",
    name: "Andorra",
    cca2: "ad",
    flagUrl: "https://flagcdn.com/w80/ad.png",
  },
  {
    id: "+257",
    name: "Burundi",
    cca2: "bi",
    flagUrl: "https://flagcdn.com/w80/bi.png",
  },
  {
    id: "+27",
    name: "South Africa",
    cca2: "za",
    flagUrl: "https://flagcdn.com/w80/za.png",
  },
  {
    id: "+33",
    name: "France",
    cca2: "fr",
    flagUrl: "https://flagcdn.com/w80/fr.png",
  },
  {
    id: "+218",
    name: "Libya",
    cca2: "ly",
    flagUrl: "https://flagcdn.com/w80/ly.png",
  },
  {
    id: "+52",
    name: "Mexico",
    cca2: "mx",
    flagUrl: "https://flagcdn.com/w80/mx.png",
  },
  {
    id: "+241",
    name: "Gabon",
    cca2: "ga",
    flagUrl: "https://flagcdn.com/w80/ga.png",
  },
  {
    id: "+1670",
    name: "Northern Mariana Islands",
    cca2: "mp",
    flagUrl: "https://flagcdn.com/w80/mp.png",
  },
  {
    id: "+389",
    name: "North Macedonia",
    cca2: "mk",
    flagUrl: "https://flagcdn.com/w80/mk.png",
  },
  {
    id: "+86",
    name: "China",
    cca2: "cn",
    flagUrl: "https://flagcdn.com/w80/cn.png",
  },
  {
    id: "+967",
    name: "Yemen",
    cca2: "ye",
    flagUrl: "https://flagcdn.com/w80/ye.png",
  },
  {
    id: "+590",
    name: "Saint Barthélemy",
    cca2: "bl",
    flagUrl: "https://flagcdn.com/w80/bl.png",
  },
  {
    id: "+44",
    name: "Guernsey",
    cca2: "gg",
    flagUrl: "https://flagcdn.com/w80/gg.png",
  },
  {
    id: "+677",
    name: "Solomon Islands",
    cca2: "sb",
    flagUrl: "https://flagcdn.com/w80/sb.png",
  },
  {
    id: "+4779",
    name: "Svalbard and Jan Mayen",
    cca2: "sj",
    flagUrl: "https://flagcdn.com/w80/sj.png",
  },
  {
    id: "+298",
    name: "Faroe Islands",
    cca2: "fo",
    flagUrl: "https://flagcdn.com/w80/fo.png",
  },
  {
    id: "+998",
    name: "Uzbekistan",
    cca2: "uz",
    flagUrl: "https://flagcdn.com/w80/uz.png",
  },
  {
    id: "+20",
    name: "Egypt",
    cca2: "eg",
    flagUrl: "https://flagcdn.com/w80/eg.png",
  },
  {
    id: "+221",
    name: "Senegal",
    cca2: "sn",
    flagUrl: "https://flagcdn.com/w80/sn.png",
  },
  {
    id: "+94",
    name: "Sri Lanka",
    cca2: "lk",
    flagUrl: "https://flagcdn.com/w80/lk.png",
  },
  {
    id: "+970",
    name: "Palestine",
    cca2: "ps",
    flagUrl: "https://flagcdn.com/w80/ps.png",
  },
  {
    id: "+880",
    name: "Bangladesh",
    cca2: "bd",
    flagUrl: "https://flagcdn.com/w80/bd.png",
  },
  {
    id: "+51",
    name: "Peru",
    cca2: "pe",
    flagUrl: "https://flagcdn.com/w80/pe.png",
  },
  {
    id: "+65",
    name: "Singapore",
    cca2: "sg",
    flagUrl: "https://flagcdn.com/w80/sg.png",
  },
  {
    id: "+90",
    name: "Turkey",
    cca2: "tr",
    flagUrl: "https://flagcdn.com/w80/tr.png",
  },
  {
    id: "+93",
    name: "Afghanistan",
    cca2: "af",
    flagUrl: "https://flagcdn.com/w80/af.png",
  },
  {
    id: "+297",
    name: "Aruba",
    cca2: "aw",
    flagUrl: "https://flagcdn.com/w80/aw.png",
  },
  {
    id: "+682",
    name: "Cook Islands",
    cca2: "ck",
    flagUrl: "https://flagcdn.com/w80/ck.png",
  },
  {
    id: "+44",
    name: "United Kingdom",
    cca2: "gb",
    flagUrl: "https://flagcdn.com/w80/gb.png",
  },
  {
    id: "+260",
    name: "Zambia",
    cca2: "zm",
    flagUrl: "https://flagcdn.com/w80/zm.png",
  },
  {
    id: "+358",
    name: "Finland",
    cca2: "fi",
    flagUrl: "https://flagcdn.com/w80/fi.png",
  },
  {
    id: "+227",
    name: "Niger",
    cca2: "ne",
    flagUrl: "https://flagcdn.com/w80/ne.png",
  },
  {
    id: "+61",
    name: "Christmas Island",
    cca2: "cx",
    flagUrl: "https://flagcdn.com/w80/cx.png",
  },
  {
    id: "+690",
    name: "Tokelau",
    cca2: "tk",
    flagUrl: "https://flagcdn.com/w80/tk.png",
  },
  {
    id: "+245",
    name: "Guinea-Bissau",
    cca2: "gw",
    flagUrl: "https://flagcdn.com/w80/gw.png",
  },
  {
    id: "+994",
    name: "Azerbaijan",
    cca2: "az",
    flagUrl: "https://flagcdn.com/w80/az.png",
  },
  {
    id: "+262",
    name: "Réunion",
    cca2: "re",
    flagUrl: "https://flagcdn.com/w80/re.png",
  },
  {
    id: "+253",
    name: "Djibouti",
    cca2: "dj",
    flagUrl: "https://flagcdn.com/w80/dj.png",
  },
  {
    id: "+850",
    name: "North Korea",
    cca2: "kp",
    flagUrl: "https://flagcdn.com/w80/kp.png",
  },
  {
    id: "+230",
    name: "Mauritius",
    cca2: "mu",
    flagUrl: "https://flagcdn.com/w80/mu.png",
  },
  {
    id: "+1664",
    name: "Montserrat",
    cca2: "ms",
    flagUrl: "https://flagcdn.com/w80/ms.png",
  },
  {
    id: "+1340",
    name: "United States Virgin Islands",
    cca2: "vi",
    flagUrl: "https://flagcdn.com/w80/vi.png",
  },
  {
    id: "+57",
    name: "Colombia",
    cca2: "co",
    flagUrl: "https://flagcdn.com/w80/co.png",
  },
  {
    id: "+30",
    name: "Greece",
    cca2: "gr",
    flagUrl: "https://flagcdn.com/w80/gr.png",
  },
  {
    id: "+385",
    name: "Croatia",
    cca2: "hr",
    flagUrl: "https://flagcdn.com/w80/hr.png",
  },
  {
    id: "+212",
    name: "Morocco",
    cca2: "ma",
    flagUrl: "https://flagcdn.com/w80/ma.png",
  },
  {
    id: "+213",
    name: "Algeria",
    cca2: "dz",
    flagUrl: "https://flagcdn.com/w80/dz.png",
  },
  {
    id: "+31",
    name: "Netherlands",
    cca2: "nl",
    flagUrl: "https://flagcdn.com/w80/nl.png",
  },
  {
    id: "+249",
    name: "Sudan",
    cca2: "sd",
    flagUrl: "https://flagcdn.com/w80/sd.png",
  },
  {
    id: "+679",
    name: "Fiji",
    cca2: "fj",
    flagUrl: "https://flagcdn.com/w80/fj.png",
  },
  {
    id: "+423",
    name: "Liechtenstein",
    cca2: "li",
    flagUrl: "https://flagcdn.com/w80/li.png",
  },
  {
    id: "+977",
    name: "Nepal",
    cca2: "np",
    flagUrl: "https://flagcdn.com/w80/np.png",
  },
  {
    id: "+1787",
    name: "Puerto Rico",
    cca2: "pr",
    flagUrl: "https://flagcdn.com/w80/pr.png",
  },
  {
    id: "+995",
    name: "Georgia",
    cca2: "ge",
    flagUrl: "https://flagcdn.com/w80/ge.png",
  },
  {
    id: "+92",
    name: "Pakistan",
    cca2: "pk",
    flagUrl: "https://flagcdn.com/w80/pk.png",
  },
  {
    id: "+377",
    name: "Monaco",
    cca2: "mc",
    flagUrl: "https://flagcdn.com/w80/mc.png",
  },
  {
    id: "+267",
    name: "Botswana",
    cca2: "bw",
    flagUrl: "https://flagcdn.com/w80/bw.png",
  },
  {
    id: "+961",
    name: "Lebanon",
    cca2: "lb",
    flagUrl: "https://flagcdn.com/w80/lb.png",
  },
  {
    id: "+675",
    name: "Papua New Guinea",
    cca2: "pg",
    flagUrl: "https://flagcdn.com/w80/pg.png",
  },
  {
    id: "+262",
    name: "Mayotte",
    cca2: "yt",
    flagUrl: "https://flagcdn.com/w80/yt.png",
  },
  {
    id: "+1809",
    name: "Dominican Republic",
    cca2: "do",
    flagUrl: "https://flagcdn.com/w80/do.png",
  },
  {
    id: "+672",
    name: "Norfolk Island",
    cca2: "nf",
    flagUrl: "https://flagcdn.com/w80/nf.png",
  },
  {
    id: "+47",
    name: "Bouvet Island",
    cca2: "bv",
    flagUrl: "https://flagcdn.com/w80/bv.png",
  },
  {
    id: "+974",
    name: "Qatar",
    cca2: "qa",
    flagUrl: "https://flagcdn.com/w80/qa.png",
  },
  {
    id: "+261",
    name: "Madagascar",
    cca2: "mg",
    flagUrl: "https://flagcdn.com/w80/mg.png",
  },
  {
    id: "+91",
    name: "India",
    cca2: "in",
    flagUrl: "https://flagcdn.com/w80/in.png",
  },
  {
    id: "+963",
    name: "Syria",
    cca2: "sy",
    flagUrl: "https://flagcdn.com/w80/sy.png",
  },
  {
    id: "+382",
    name: "Montenegro",
    cca2: "me",
    flagUrl: "https://flagcdn.com/w80/me.png",
  },
  {
    id: "+268",
    name: "Eswatini",
    cca2: "sz",
    flagUrl: "https://flagcdn.com/w80/sz.png",
  },
  {
    id: "+595",
    name: "Paraguay",
    cca2: "py",
    flagUrl: "https://flagcdn.com/w80/py.png",
  },
  {
    id: "+503",
    name: "El Salvador",
    cca2: "sv",
    flagUrl: "https://flagcdn.com/w80/sv.png",
  },
  {
    id: "+380",
    name: "Ukraine",
    cca2: "ua",
    flagUrl: "https://flagcdn.com/w80/ua.png",
  },
  {
    id: "+44",
    name: "Isle of Man",
    cca2: "im",
    flagUrl: "https://flagcdn.com/w80/im.png",
  },
  {
    id: "+264",
    name: "Namibia",
    cca2: "na",
    flagUrl: "https://flagcdn.com/w80/na.png",
  },
  {
    id: "+971",
    name: "United Arab Emirates",
    cca2: "ae",
    flagUrl: "https://flagcdn.com/w80/ae.png",
  },
  {
    id: "+359",
    name: "Bulgaria",
    cca2: "bg",
    flagUrl: "https://flagcdn.com/w80/bg.png",
  },
  {
    id: "+299",
    name: "Greenland",
    cca2: "gl",
    flagUrl: "https://flagcdn.com/w80/gl.png",
  },
  {
    id: "+49",
    name: "Germany",
    cca2: "de",
    flagUrl: "https://flagcdn.com/w80/de.png",
  },
  {
    id: "+855",
    name: "Cambodia",
    cca2: "kh",
    flagUrl: "https://flagcdn.com/w80/kh.png",
  },
  {
    id: "+964",
    name: "Iraq",
    cca2: "iq",
    flagUrl: "https://flagcdn.com/w80/iq.png",
  },
  {
    id: "+262",
    name: "French Southern and Antarctic Lands",
    cca2: "tf",
    flagUrl: "https://flagcdn.com/w80/tf.png",
  },
  {
    id: "+46",
    name: "Sweden",
    cca2: "se",
    flagUrl: "https://flagcdn.com/w80/se.png",
  },
  {
    id: "+53",
    name: "Cuba",
    cca2: "cu",
    flagUrl: "https://flagcdn.com/w80/cu.png",
  },
  {
    id: "+996",
    name: "Kyrgyzstan",
    cca2: "kg",
    flagUrl: "https://flagcdn.com/w80/kg.png",
  },
  {
    id: "+73",
    name: "Russia",
    cca2: "ru",
    flagUrl: "https://flagcdn.com/w80/ru.png",
  },
  {
    id: "+60",
    name: "Malaysia",
    cca2: "my",
    flagUrl: "https://flagcdn.com/w80/my.png",
  },
  {
    id: "+239",
    name: "São Tomé and Príncipe",
    cca2: "st",
    flagUrl: "https://flagcdn.com/w80/st.png",
  },
  {
    id: "+357",
    name: "Cyprus",
    cca2: "cy",
    flagUrl: "https://flagcdn.com/w80/cy.png",
  },
  {
    id: "+1",
    name: "Canada",
    cca2: "ca",
    flagUrl: "https://flagcdn.com/w80/ca.png",
  },
  {
    id: "+265",
    name: "Malawi",
    cca2: "mw",
    flagUrl: "https://flagcdn.com/w80/mw.png",
  },
  {
    id: "+966",
    name: "Saudi Arabia",
    cca2: "sa",
    flagUrl: "https://flagcdn.com/w80/sa.png",
  },
  {
    id: "+387",
    name: "Bosnia and Herzegovina",
    cca2: "ba",
    flagUrl: "https://flagcdn.com/w80/ba.png",
  },
  {
    id: "+251",
    name: "Ethiopia",
    cca2: "et",
    flagUrl: "https://flagcdn.com/w80/et.png",
  },
  {
    id: "+34",
    name: "Spain",
    cca2: "es",
    flagUrl: "https://flagcdn.com/w80/es.png",
  },
  {
    id: "+386",
    name: "Slovenia",
    cca2: "si",
    flagUrl: "https://flagcdn.com/w80/si.png",
  },
  {
    id: "+968",
    name: "Oman",
    cca2: "om",
    flagUrl: "https://flagcdn.com/w80/om.png",
  },
  {
    id: "+508",
    name: "Saint Pierre and Miquelon",
    cca2: "pm",
    flagUrl: "https://flagcdn.com/w80/pm.png",
  },
  {
    id: "+853",
    name: "Macau",
    cca2: "mo",
    flagUrl: "https://flagcdn.com/w80/mo.png",
  },
  {
    id: "+378",
    name: "San Marino",
    cca2: "sm",
    flagUrl: "https://flagcdn.com/w80/sm.png",
  },
  {
    id: "+266",
    name: "Lesotho",
    cca2: "ls",
    flagUrl: "https://flagcdn.com/w80/ls.png",
  },
  {
    id: "+692",
    name: "Marshall Islands",
    cca2: "mh",
    flagUrl: "https://flagcdn.com/w80/mh.png",
  },
  {
    id: "+1721",
    name: "Sint Maarten",
    cca2: "sx",
    flagUrl: "https://flagcdn.com/w80/sx.png",
  },
  {
    id: "+354",
    name: "Iceland",
    cca2: "is",
    flagUrl: "https://flagcdn.com/w80/is.png",
  },
  {
    id: "+352",
    name: "Luxembourg",
    cca2: "lu",
    flagUrl: "https://flagcdn.com/w80/lu.png",
  },
  {
    id: "+54",
    name: "Argentina",
    cca2: "ar",
    flagUrl: "https://flagcdn.com/w80/ar.png",
  },
  {
    id: "+1649",
    name: "Turks and Caicos Islands",
    cca2: "tc",
    flagUrl: "https://flagcdn.com/w80/tc.png",
  },
  {
    id: "+674",
    name: "Nauru",
    cca2: "nr",
    flagUrl: "https://flagcdn.com/w80/nr.png",
  },
  {
    id: "+61",
    name: "Cocos (Keeling) Islands",
    cca2: "cc",
    flagUrl: "https://flagcdn.com/w80/cc.png",
  },
  {
    id: "+2125288",
    name: "Western Sahara",
    cca2: "eh",
    flagUrl: "https://flagcdn.com/w80/eh.png",
  },
  {
    id: "+1767",
    name: "Dominica",
    cca2: "dm",
    flagUrl: "https://flagcdn.com/w80/dm.png",
  },
  {
    id: "+506",
    name: "Costa Rica",
    cca2: "cr",
    flagUrl: "https://flagcdn.com/w80/cr.png",
  },
  {
    id: "+61",
    name: "Australia",
    cca2: "au",
    flagUrl: "https://flagcdn.com/w80/au.png",
  },
  {
    id: "+66",
    name: "Thailand",
    cca2: "th",
    flagUrl: "https://flagcdn.com/w80/th.png",
  },
  {
    id: "+509",
    name: "Haiti",
    cca2: "ht",
    flagUrl: "https://flagcdn.com/w80/ht.png",
  },
  {
    id: "+688",
    name: "Tuvalu",
    cca2: "tv",
    flagUrl: "https://flagcdn.com/w80/tv.png",
  },
  {
    id: "+504",
    name: "Honduras",
    cca2: "hn",
    flagUrl: "https://flagcdn.com/w80/hn.png",
  },
  {
    id: "+240",
    name: "Equatorial Guinea",
    cca2: "gq",
    flagUrl: "https://flagcdn.com/w80/gq.png",
  },
  {
    id: "+1758",
    name: "Saint Lucia",
    cca2: "lc",
    flagUrl: "https://flagcdn.com/w80/lc.png",
  },
  {
    id: "+689",
    name: "French Polynesia",
    cca2: "pf",
    flagUrl: "https://flagcdn.com/w80/pf.png",
  },
  {
    id: "+375",
    name: "Belarus",
    cca2: "by",
    flagUrl: "https://flagcdn.com/w80/by.png",
  },
  {
    id: "+371",
    name: "Latvia",
    cca2: "lv",
    flagUrl: "https://flagcdn.com/w80/lv.png",
  },
  {
    id: "+680",
    name: "Palau",
    cca2: "pw",
    flagUrl: "https://flagcdn.com/w80/pw.png",
  },
  {
    id: "+590",
    name: "Guadeloupe",
    cca2: "gp",
    flagUrl: "https://flagcdn.com/w80/gp.png",
  },
  {
    id: "+63",
    name: "Philippines",
    cca2: "ph",
    flagUrl: "https://flagcdn.com/w80/ph.png",
  },
  {
    id: "+350",
    name: "Gibraltar",
    cca2: "gi",
    flagUrl: "https://flagcdn.com/w80/gi.png",
  },
  {
    id: "+45",
    name: "Denmark",
    cca2: "dk",
    flagUrl: "https://flagcdn.com/w80/dk.png",
  },
  {
    id: "+237",
    name: "Cameroon",
    cca2: "cm",
    flagUrl: "https://flagcdn.com/w80/cm.png",
  },
  {
    id: "+224",
    name: "Guinea",
    cca2: "gn",
    flagUrl: "https://flagcdn.com/w80/gn.png",
  },
  {
    id: "+973",
    name: "Bahrain",
    cca2: "bh",
    flagUrl: "https://flagcdn.com/w80/bh.png",
  },
  {
    id: "+597",
    name: "Suriname",
    cca2: "sr",
    flagUrl: "https://flagcdn.com/w80/sr.png",
  },
  {
    id: "+243",
    name: "DR Congo",
    cca2: "cd",
    flagUrl: "https://flagcdn.com/w80/cd.png",
  },
  {
    id: "+252",
    name: "Somalia",
    cca2: "so",
    flagUrl: "https://flagcdn.com/w80/so.png",
  },
  {
    id: "+420",
    name: "Czechia",
    cca2: "cz",
    flagUrl: "https://flagcdn.com/w80/cz.png",
  },
  {
    id: "+687",
    name: "New Caledonia",
    cca2: "nc",
    flagUrl: "https://flagcdn.com/w80/nc.png",
  },
  {
    id: "+678",
    name: "Vanuatu",
    cca2: "vu",
    flagUrl: "https://flagcdn.com/w80/vu.png",
  },
  {
    id: "+290",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    cca2: "sh",
    flagUrl: "https://flagcdn.com/w80/sh.png",
  },
  {
    id: "+228",
    name: "Togo",
    cca2: "tg",
    flagUrl: "https://flagcdn.com/w80/tg.png",
  },
  {
    id: "+1284",
    name: "British Virgin Islands",
    cca2: "vg",
    flagUrl: "https://flagcdn.com/w80/vg.png",
  },
  {
    id: "+254",
    name: "Kenya",
    cca2: "ke",
    flagUrl: "https://flagcdn.com/w80/ke.png",
  },
  {
    id: "+683",
    name: "Niue",
    cca2: "nu",
    flagUrl: "https://flagcdn.com/w80/nu.png",
  },
  {
    id: "+250",
    name: "Rwanda",
    cca2: "rw",
    flagUrl: "https://flagcdn.com/w80/rw.png",
  },
  {
    id: "+372",
    name: "Estonia",
    cca2: "ee",
    flagUrl: "https://flagcdn.com/w80/ee.png",
  },
  {
    id: "+40",
    name: "Romania",
    cca2: "ro",
    flagUrl: "https://flagcdn.com/w80/ro.png",
  },
  {
    id: "+1868",
    name: "Trinidad and Tobago",
    cca2: "tt",
    flagUrl: "https://flagcdn.com/w80/tt.png",
  },
  {
    id: "+592",
    name: "Guyana",
    cca2: "gy",
    flagUrl: "https://flagcdn.com/w80/gy.png",
  },
  {
    id: "+670",
    name: "Timor-Leste",
    cca2: "tl",
    flagUrl: "https://flagcdn.com/w80/tl.png",
  },
  {
    id: "+84",
    name: "Vietnam",
    cca2: "vn",
    flagUrl: "https://flagcdn.com/w80/vn.png",
  },
  {
    id: "+598",
    name: "Uruguay",
    cca2: "uy",
    flagUrl: "https://flagcdn.com/w80/uy.png",
  },
  {
    id: "+3906698",
    name: "Vatican City",
    cca2: "va",
    flagUrl: "https://flagcdn.com/w80/va.png",
  },
  {
    id: "+852",
    name: "Hong Kong",
    cca2: "hk",
    flagUrl: "https://flagcdn.com/w80/hk.png",
  },
  {
    id: "+43",
    name: "Austria",
    cca2: "at",
    flagUrl: "https://flagcdn.com/w80/at.png",
  },
  {
    id: "+1268",
    name: "Antigua and Barbuda",
    cca2: "ag",
    flagUrl: "https://flagcdn.com/w80/ag.png",
  },
  {
    id: "+993",
    name: "Turkmenistan",
    cca2: "tm",
    flagUrl: "https://flagcdn.com/w80/tm.png",
  },
  {
    id: "+258",
    name: "Mozambique",
    cca2: "mz",
    flagUrl: "https://flagcdn.com/w80/mz.png",
  },
  {
    id: "+507",
    name: "Panama",
    cca2: "pa",
    flagUrl: "https://flagcdn.com/w80/pa.png",
  },
  {
    id: "+691",
    name: "Micronesia",
    cca2: "fm",
    flagUrl: "https://flagcdn.com/w80/fm.png",
  },
  {
    id: "+353",
    name: "Ireland",
    cca2: "ie",
    flagUrl: "https://flagcdn.com/w80/ie.png",
  },
  {
    id: "+599",
    name: "Curaçao",
    cca2: "cw",
    flagUrl: "https://flagcdn.com/w80/cw.png",
  },
  {
    id: "+594",
    name: "French Guiana",
    cca2: "gf",
    flagUrl: "https://flagcdn.com/w80/gf.png",
  },
  {
    id: "+47",
    name: "Norway",
    cca2: "no",
    flagUrl: "https://flagcdn.com/w80/no.png",
  },
  {
    id: "+35818",
    name: "Åland Islands",
    cca2: "ax",
    flagUrl: "https://flagcdn.com/w80/ax.png",
  },
  {
    id: "+236",
    name: "Central African Republic",
    cca2: "cf",
    flagUrl: "https://flagcdn.com/w80/cf.png",
  },
  {
    id: "+226",
    name: "Burkina Faso",
    cca2: "bf",
    flagUrl: "https://flagcdn.com/w80/bf.png",
  },
  {
    id: "+291",
    name: "Eritrea",
    cca2: "er",
    flagUrl: "https://flagcdn.com/w80/er.png",
  },
  {
    id: "+255",
    name: "Tanzania",
    cca2: "tz",
    flagUrl: "https://flagcdn.com/w80/tz.png",
  },
  {
    id: "+82",
    name: "South Korea",
    cca2: "kr",
    flagUrl: "https://flagcdn.com/w80/kr.png",
  },
  {
    id: "+962",
    name: "Jordan",
    cca2: "jo",
    flagUrl: "https://flagcdn.com/w80/jo.png",
  },
  {
    id: "+222",
    name: "Mauritania",
    cca2: "mr",
    flagUrl: "https://flagcdn.com/w80/mr.png",
  },
  {
    id: "+370",
    name: "Lithuania",
    cca2: "lt",
    flagUrl: "https://flagcdn.com/w80/lt.png",
  },
  {
    id: "+268",
    name: "United States Minor Outlying Islands",
    cca2: "um",
    flagUrl: "https://flagcdn.com/w80/um.png",
  },
  {
    id: "+421",
    name: "Slovakia",
    cca2: "sk",
    flagUrl: "https://flagcdn.com/w80/sk.png",
  },
  {
    id: "+244",
    name: "Angola",
    cca2: "ao",
    flagUrl: "https://flagcdn.com/w80/ao.png",
  },
  {
    id: "+76",
    name: "Kazakhstan",
    cca2: "kz",
    flagUrl: "https://flagcdn.com/w80/kz.png",
  },
  {
    id: "+373",
    name: "Moldova",
    cca2: "md",
    flagUrl: "https://flagcdn.com/w80/md.png",
  },
  {
    id: "+223",
    name: "Mali",
    cca2: "ml",
    flagUrl: "https://flagcdn.com/w80/ml.png",
  },
  {
    id: "+500",
    name: "Falkland Islands",
    cca2: "fk",
    flagUrl: "https://flagcdn.com/w80/fk.png",
  },
  {
    id: "+374",
    name: "Armenia",
    cca2: "am",
    flagUrl: "https://flagcdn.com/w80/am.png",
  },
  {
    id: "+685",
    name: "Samoa",
    cca2: "ws",
    flagUrl: "https://flagcdn.com/w80/ws.png",
  },
  {
    id: "+44",
    name: "Jersey",
    cca2: "je",
    flagUrl: "https://flagcdn.com/w80/je.png",
  },
  {
    id: "+81",
    name: "Japan",
    cca2: "jp",
    flagUrl: "https://flagcdn.com/w80/jp.png",
  },
  {
    id: "+591",
    name: "Bolivia",
    cca2: "bo",
    flagUrl: "https://flagcdn.com/w80/bo.png",
  },
  {
    id: "+56",
    name: "Chile",
    cca2: "cl",
    flagUrl: "https://flagcdn.com/w80/cl.png",
  },
  {
    id: "+1201",
    name: "United States",
    cca2: "us",
    flagUrl: "https://flagcdn.com/w80/us.png",
  },
  {
    id: "+1784",
    name: "Saint Vincent and the Grenadines",
    cca2: "vc",
    flagUrl: "https://flagcdn.com/w80/vc.png",
  },
  {
    id: "+1441",
    name: "Bermuda",
    cca2: "bm",
    flagUrl: "https://flagcdn.com/w80/bm.png",
  },
  {
    id: "+248",
    name: "Seychelles",
    cca2: "sc",
    flagUrl: "https://flagcdn.com/w80/sc.png",
  },
  {
    id: "+246",
    name: "British Indian Ocean Territory",
    cca2: "io",
    flagUrl: "https://flagcdn.com/w80/io.png",
  },
  {
    id: "+502",
    name: "Guatemala",
    cca2: "gt",
    flagUrl: "https://flagcdn.com/w80/gt.png",
  },
  {
    id: "+593",
    name: "Ecuador",
    cca2: "ec",
    flagUrl: "https://flagcdn.com/w80/ec.png",
  },
  {
    id: "+596",
    name: "Martinique",
    cca2: "mq",
    flagUrl: "https://flagcdn.com/w80/mq.png",
  },
  {
    id: "+992",
    name: "Tajikistan",
    cca2: "tj",
    flagUrl: "https://flagcdn.com/w80/tj.png",
  },
  {
    id: "+356",
    name: "Malta",
    cca2: "mt",
    flagUrl: "https://flagcdn.com/w80/mt.png",
  },
  {
    id: "+220",
    name: "Gambia",
    cca2: "gm",
    flagUrl: "https://flagcdn.com/w80/gm.png",
  },
  {
    id: "+234",
    name: "Nigeria",
    cca2: "ng",
    flagUrl: "https://flagcdn.com/w80/ng.png",
  },
  {
    id: "+1242",
    name: "Bahamas",
    cca2: "bs",
    flagUrl: "https://flagcdn.com/w80/bs.png",
  },
  {
    id: "+383",
    name: "Kosovo",
    cca2: "xk",
    flagUrl: "https://flagcdn.com/w80/xk.png",
  },
  {
    id: "+965",
    name: "Kuwait",
    cca2: "kw",
    flagUrl: "https://flagcdn.com/w80/kw.png",
  },
  {
    id: "+960",
    name: "Maldives",
    cca2: "mv",
    flagUrl: "https://flagcdn.com/w80/mv.png",
  },
  {
    id: "+211",
    name: "South Sudan",
    cca2: "ss",
    flagUrl: "https://flagcdn.com/w80/ss.png",
  },
  {
    id: "+98",
    name: "Iran",
    cca2: "ir",
    flagUrl: "https://flagcdn.com/w80/ir.png",
  },
  {
    id: "+355",
    name: "Albania",
    cca2: "al",
    flagUrl: "https://flagcdn.com/w80/al.png",
  },
  {
    id: "+55",
    name: "Brazil",
    cca2: "br",
    flagUrl: "https://flagcdn.com/w80/br.png",
  },
  {
    id: "+381",
    name: "Serbia",
    cca2: "rs",
    flagUrl: "https://flagcdn.com/w80/rs.png",
  },
  {
    id: "+501",
    name: "Belize",
    cca2: "bz",
    flagUrl: "https://flagcdn.com/w80/bz.png",
  },
  {
    id: "+95",
    name: "Myanmar",
    cca2: "mm",
    flagUrl: "https://flagcdn.com/w80/mm.png",
  },
  {
    id: "+975",
    name: "Bhutan",
    cca2: "bt",
    flagUrl: "https://flagcdn.com/w80/bt.png",
  },
  {
    id: "+58",
    name: "Venezuela",
    cca2: "ve",
    flagUrl: "https://flagcdn.com/w80/ve.png",
  },
  {
    id: "+231",
    name: "Liberia",
    cca2: "lr",
    flagUrl: "https://flagcdn.com/w80/lr.png",
  },
  {
    id: "+1876",
    name: "Jamaica",
    cca2: "jm",
    flagUrl: "https://flagcdn.com/w80/jm.png",
  },
  {
    id: "+48",
    name: "Poland",
    cca2: "pl",
    flagUrl: "https://flagcdn.com/w80/pl.png",
  },
  {
    id: "+1345",
    name: "Cayman Islands",
    cca2: "ky",
    flagUrl: "https://flagcdn.com/w80/ky.png",
  },
  {
    id: "+673",
    name: "Brunei",
    cca2: "bn",
    flagUrl: "https://flagcdn.com/w80/bn.png",
  },
  {
    id: "+269",
    name: "Comoros",
    cca2: "km",
    flagUrl: "https://flagcdn.com/w80/km.png",
  },
  {
    id: "+1671",
    name: "Guam",
    cca2: "gu",
    flagUrl: "https://flagcdn.com/w80/gu.png",
  },
  {
    id: "+676",
    name: "Tonga",
    cca2: "to",
    flagUrl: "https://flagcdn.com/w80/to.png",
  },
  {
    id: "+686",
    name: "Kiribati",
    cca2: "ki",
    flagUrl: "https://flagcdn.com/w80/ki.png",
  },
  {
    id: "+233",
    name: "Ghana",
    cca2: "gh",
    flagUrl: "https://flagcdn.com/w80/gh.png",
  },
  {
    id: "+235",
    name: "Chad",
    cca2: "td",
    flagUrl: "https://flagcdn.com/w80/td.png",
  },
  {
    id: "+263",
    name: "Zimbabwe",
    cca2: "zw",
    flagUrl: "https://flagcdn.com/w80/zw.png",
  },
  {
    id: "+590",
    name: "Saint Martin",
    cca2: "mf",
    flagUrl: "https://flagcdn.com/w80/mf.png",
  },
  {
    id: "+976",
    name: "Mongolia",
    cca2: "mn",
    flagUrl: "https://flagcdn.com/w80/mn.png",
  },
  {
    id: "+351",
    name: "Portugal",
    cca2: "pt",
    flagUrl: "https://flagcdn.com/w80/pt.png",
  },
  {
    id: "+1684",
    name: "American Samoa",
    cca2: "as",
    flagUrl: "https://flagcdn.com/w80/as.png",
  },
  {
    id: "+242",
    name: "Republic of the Congo",
    cca2: "cg",
    flagUrl: "https://flagcdn.com/w80/cg.png",
  },
  {
    id: "+32",
    name: "Belgium",
    cca2: "be",
    flagUrl: "https://flagcdn.com/w80/be.png",
  },
  {
    id: "+972",
    name: "Israel",
    cca2: "il",
    flagUrl: "https://flagcdn.com/w80/il.png",
  },
  {
    id: "+64",
    name: "New Zealand",
    cca2: "nz",
    flagUrl: "https://flagcdn.com/w80/nz.png",
  },
  {
    id: "+505",
    name: "Nicaragua",
    cca2: "ni",
    flagUrl: "https://flagcdn.com/w80/ni.png",
  },
  {
    id: "+1264",
    name: "Anguilla",
    cca2: "ai",
    flagUrl: "https://flagcdn.com/w80/ai.png",
  },
];

const sortCountriesByName = () => {
  return COUNTRIES.sort((a, b) => {
    if (a.name < b.name) return -1;
    if (a.name > b.name) return 1;
    return 0;
  });
};

export { COUNTRIES, sortCountriesByName };
